duckdb_lakehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /home/anton1/data-projects/10_DuckLake-dbt/lakehouse.duckdb          # путь к файлу .duckdb
      threads: 1
      extensions:
        - httpfs
      settings:
        s3_region: us-east-1
        s3_endpoint: localhost:9000
        s3_access_key_id: minioadmin
        s3_secret_access_key: minioadmin
        s3_url_style: path
        s3_use_ssl: false